# Generated by Django 4.2.1 on 2023-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0006_alter_iteminauction_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminauction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='iteminauction',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
