# Generated by Django 4.2.1 on 2023-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0010_alter_iteminauction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminauction',
            name='name',
            field=models.TextField(max_length=60, unique=True, verbose_name='Item name'),
        ),
    ]
