# Generated by Django 4.2.1 on 2023-05-26 00:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_api', '0012_alter_iteminauction_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminauction',
            name='item_owner',
            field=models.ForeignKey(help_text='Determine which user the item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items_api.user', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='iteminauction',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price of item'),
        ),
    ]
