# Generated by Django 4.2.1 on 2023-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='User email')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='User age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
