# Generated by Django 4.2.1 on 2023-05-11 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, unique=True, verbose_name='User email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='User name'),
            preserve_default=False,
        ),
    ]
